### ISSUE TITLE
[doc] icinga2 client configuration in pillar.example is not a valid yaml

### ISSUE THREAD

**Issue by Yoda-BZH** [hemebond/icinga2-formula#2]
Hello,

in the pillar.example, when configuring the client part of icinga :
https://github.com/hemebond/icinga2-formula/blob/master/pillar.example#L66-L69

```
      endpoint:
        NodeName: {}
        icinga2master.example.com
          host: icinga2master.example.com
```

Those lines are not valid yaml data.

Can the pillar.example be corrected please ?
